.github/workflows/build.yaml
ci/playbook.yml
src/chart/Chart.yaml
src/chart/templates/_helpers.tpl
src/version.json

This PR scaffolds the repository layout.
It adds an (empty) Helm chart, and a GitHub action which will build and publish the Helm chart as an artifact.
It also adds an Ansible workflow which can be used to make sure all dependencies (such as k3d, kubectl, docker or helm) are installed.

Scaffold repository layout, Helm chart

---

.github/workflows/build.yaml
ci/playbook.yml

- Set the Helm chart `appVersion` and `version` during CI, based on the output of `nbgv`.
- Deploy the Helm chart to a k3d cluster

Deploy Helm chart during CI

---

.github/workflows/images.yaml
src/iproxy/Dockerfile
src/iproxy/Makefile

- Build Docker image for `iproxy` for amd64 and arm64 Linux, and generate a multi-arch manifest
- Add a CI pipeline to validate the script

Add iproxy image

---

.github/workflows/images.yaml
src/iproxy/Dockerfile
src/usbmuxd/Dockerfile
src/usbmuxd/Makefile

This adds an amd64 and arm64 image for usbmuxd.
The arm64 image is cross-built form amd64 to arm64 using the Debian multi-arch features.

Add usbmuxd image

---

src/Kaponata.iOS.Tests/Muxer/DeviceAttachedMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/DeviceDetachedMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/DevicePairedMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/ListenMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.cs
src/Kaponata.iOS.Tests/Muxer/MuxerExceptionTests.cs
src/Kaponata.iOS.Tests/Muxer/MuxerMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/MuxerProtocolTests.cs
src/Kaponata.iOS.Tests/Muxer/ResultMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/attached.xml
src/Kaponata.iOS.Tests/Muxer/detached.xml
src/Kaponata.iOS.Tests/Muxer/listen.xml
src/Kaponata.iOS.Tests/Muxer/paired.xml
src/Kaponata.iOS.Tests/Muxer/result.xml
src/Kaponata.iOS/Muxer/DeviceDetachedMessage.Serialization.cs
src/Kaponata.iOS/Muxer/DeviceDetachedMessage.cs
src/Kaponata.iOS/Muxer/DevicePairedMessage.Serialization.cs
src/Kaponata.iOS/Muxer/DevicePairedMessage.cs
src/Kaponata.iOS/Muxer/ListenMessage.cs
src/Kaponata.iOS/Muxer/MuxerClient.List.cs
src/Kaponata.iOS/Muxer/MuxerClient.Listen.cs
src/Kaponata.iOS/Muxer/MuxerError.cs
src/Kaponata.iOS/Muxer/MuxerException.cs
src/Kaponata.iOS/Muxer/MuxerListenAction.cs
src/Kaponata.iOS/Muxer/MuxerMessage.Serialization.cs
src/Kaponata.iOS/Muxer/MuxerMessage.cs
src/Kaponata.iOS/Muxer/MuxerProtocol.cs
src/Kaponata.iOS/Muxer/ResultMessage.Serialization.cs
src/Kaponata.iOS/Muxer/ResultMessage.cs

This PR adds the `MuxerClient.ListenAsync` method, which supports listening for device attached/paired/detached events.

Add MuxerClient.ListenAsync

---

.github/workflows/images.yaml
src/usbmuxd/.gitignore
src/usbmuxd/Dockerfile.template
src/usbmuxd/Makefile
src/usbmuxd/default.yaml
src/usbmuxd/udev.yaml

By default, we build libusb with `--enable-udev=no`.
On Linux environments where usbfs is not available, `libusb_init` will
fail and usbmuxd will exit with a SIGSEV.
While it's okay for usbmuxd to fail when no USB stack is available
(no iOS devices are present either), this causes issues in CI systems,
where we'd prefer for usbmuxd to run but just report an empty device
list.
As a workaround, we can compile libusb with udev support. This will
cause libusb to report an empty device list and usbmuxd to work
correctly.
Because we don't want udev support in the main container image,
this introduces a new tag, latest-udev-amd64.
The Dockerfiles for usbmuxd with and without udev support are similar,
and are built from a template using gomplate.

usbmuxd image: Build an -udev variant

---

.github/workflows/build.yaml

The GitHub action which calculates code coverage accepts glob patterns,
but picks the first coverage report which maps that pattern.
We have multiple code coverage reports. This causes the coverage to be
posted in GitHub to be incorrect.
Instead:
- Create a consolidated code coverage report using the report generator
- Upload that report to GitHub.

Fix code coverage report

---

.github/workflows/build.yaml

The code coverage summary is published as a code comment, but the full code coverage report is not easily accessible. (It is uploaded as an artifact, but you'd need to download the artifact, unzip it and then view it).
This PR adds an action which uploads the code coverage report to the ci.kaponata.io blob storage account, and adds a comment to each PR with a link.

Upload code coverage reports to static website

---

src/Kaponata.Operator.Tests/Kaponata.Operator.Tests.csproj
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesClientTests.PortForward.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesClientTests.Watch.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesClientTests.cs
src/Kaponata.Operator.Tests/Kubernetes/PortForwardStreamTests.cs
src/Kaponata.Operator/Kubernetes/Polyfill/IKubernetesClient.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesClient.PortForward.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/PortForwardStream.cs

Returns a `Stream` which allows you to send and receive data to/from the TCP port on the pod.
The operators will need this to connect to the adb/usbmuxd port on the device daemons.

Add KubernetesClient.ConnectToPodPortAsync

---

src/usbmuxd/Dockerfile.template

libimobiledevice/usbmuxd@b1a7c7ebf110aece7175b0c4d032608a00a7b55b fixes a segmentation fault in usbmuxd (libimobiledevice/usbmuxd#161), so upgrade to the latest version.

Update usbmuxd to b1a7c7ebf110aece7175b0c4d032608a00a7b55b

---

src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.cs
src/Kaponata.iOS/Muxer/MuxerClient.cs
src/Kaponata.iOS/Muxer/MuxerSocketLocator.cs

This PR updates the `MuxerSocketLocator` class so that it returns a `Stream` which can be used by the `MuxerClient`. 
Returning a `Socket` and `EndPoint` does not always work: for example, when connecting to a port on a pod running in Kubernetes, we may only get a `Stream`, which represents the connection being tunneled over a WebSocket connection to the API server, and there isn't an actual `Socket` which we can connect to.
So this adds the `Task<Stream> MuxerSocketLocator.ConnectToMuxerAsync(CancellationToken cancellationToken)` API.

MuxerClient: Move socket handling to MuxerSocketLocator, only operate on Stream objects

---

.github/workflows/build.yaml
src/Kaponata.Chart.Tests/Kaponata.Chart.Tests.csproj
src/Kaponata.sln

This PR adds the `Kaponata.Chart.Tests` test project, and updates the CI script to run these tests when the k3d cluster is provisioned.
We can add integration tests (e.g. to verify usbmuxd is running and we can connect to the usbmuxd pods) to this project.

Scaffold integration tests for the Helm chart

---

.github/workflows/build.yaml
src/Kaponata.Operator.Tests/Kaponata.Operator.Tests.csproj
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.PortForward.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/Polyfill/IKubernetesProtocol.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.PortForward.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.cs

This PR introduces the `KubernetesClient` class (and renames the old `KubernetesClient` to `KubernetesProtocol`), which provides high-level Kubernetes tasks.
In this PR, the first methods being added are:
- `KubernetesClient.WaitForPodRunningAsync`.
- `KubernetesClient.DeletePodAsync`

Add KubernetesClient.WaitForPodRunningAsync, DeletePodAsync methods

---

.github/workflows/build.yaml
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.Watch.cs

- Add more logging and capture logs in unit tests
- Keep objects alive by wrapping them in a `using` statement
Related to #29

Troubleshoot flakiness

---

.github/workflows/build.yaml
src/Kaponata.Chart.Tests/Kaponata.Chart.Tests.csproj
src/Kaponata.Chart.Tests/UsbmuxdTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesMuxerSocketLocatorTests.cs
src/Kaponata.Operator/Kaponata.Operator.csproj
src/Kaponata.Operator/Kubernetes/KubernetesMuxerSocketLocator.cs
src/chart/.helmignore
src/chart/Chart.yaml
src/chart/Makefile
src/chart/charts/usbmuxd/Chart.yaml
src/chart/charts/usbmuxd/templates/_helpers.tpl
src/chart/charts/usbmuxd/templates/daemonset.yaml
src/chart/charts/usbmuxd/values.yaml

This PR adds an usbmuxd subchart to the kaponata chart, which will deploy an usbmuxd daemon to all nodes in the cluster.
It also introduces an integration test in the `Kaponata.Chart.Tests` project which runs when the kaponata chart is deployed to the k3d cluster. It simply connects to usbmuxd, list the devices, and makes sure no exception occurs.
As a side effect, this PR introduces the `PortForwardStream` and `KubernetesMuxerSocketLocator` classes which allow `MuxerClient` to connect to an instance of usbmuxd running in a Kubernetes pod

Add usbmuxd to Helm chart

---

.github/workflows/build.yaml
docs/KubernetesClient.md
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Delete.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/Polyfill/IKubernetesProtocol.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.Watch.cs

Add a simple API for creating, reading an deleting individual pods:
```csharp
Task<V1Pod> CreatePodAsync(V1Pod value, CancellationToken cancellationToken);
Task<V1Pod> TryReadPodAsync(string @namespace, string name, CancellationToken cancellationToken);
Task DeletePodAsync(V1Pod value, TimeSpan timeout, CancellationToken cancellationToken);
```
Have the API translate HTTP errors with `V1Status` messages into `KubernetesException` objects with a clear error message.

KubernetesClient: Update API

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.CustomResourceDefinition.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Crd.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Delete.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs

```csharp
Task<V1CustomResourceDefinition> CreateCustomResourceDefinitionAsync(V1CustomResourceDefinition value, CancellationToken cancellationToken);
Task<V1CustomResourceDefinition> TryReadCustomResourceDefinitionAsync(string name, CancellationToken cancellationToken);
Task DeleteCustomResourceDefinitionAsync(V1CustomResourceDefinition crd, TimeSpan timeout, CancellationToken cancellationToken);
```

KubernetesClient: Add methods for working with CRDs

---

.gitignore
src/Kaponata.Operator.Tests/ExtensionsInstallerTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.CustomResourceDefinition.cs
src/Kaponata.Operator.Tests/Models/ModelDefinitionsTests.cs
src/Kaponata.Operator/ExtensionsInstaller.cs
src/Kaponata.Operator/GlobalSuppressions.cs
src/Kaponata.Operator/Kaponata.Operator.csproj
src/Kaponata.Operator/Kubernetes/Annotations.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Crd.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Models/MobileDevice.yaml
src/Kaponata.Operator/Models/ModelDefinitions.cs
src/Kaponata.Operator/Program.cs
src/Kaponata.Operator/Properties/launchSettings.json
src/chart/templates/_helpers.tpl
src/chart/templates/operator-clusterRole.yaml
src/chart/templates/operator-clusterRoleBinding.yaml
src/chart/templates/operator-deployment.yaml

[Helm doesn't provide a built-in way for managing CustomResourceDefinitions](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) in Helm charts. In particular, upgrading CRDs is something that Helm doesn't support (and they have good reasons for it).
In the Kaponata project, we currently plan on two CRDs: `MobileDevice` and `WebDriverSession`.
For both CRDs, the values are not "authorative": `MobileDevice` merely reflects the mobile device data as reported by adb/usbmuxd; `WebDriverSession` is a (relatively) short-lived object which tracks an Appium session which is running.
This means that it's acceptable for us to "upgrade" CRDs by deleting them and re-creating them from scratch. We'll lose all `MobileDevice` objects but the operator will re-created them.
This PR …

Install the MobileDevice CRD into the cluster

---

.github/workflows/images.yaml
src/adb/Dockerfile
src/adb/Makefile

This PR adds the `quay.io/kaponata/adb` image. The tag is the adb version (e.g. `1.0.41`); not the platform-tools version.
The `adb` executable is extracted from the `platform-tools` package built by the upstream Android project.
There is no arm64 tag for now because the Android project doesn't provide prebuilt `adb` images.

Add adb container image

---

.github/workflows/build.yaml
ci/redroid.yaml

This PR updates the CI system so that an pod running Redroid (Android) is running inside the k3s cluster.
This should allow us to run basic integration tests inside CI.
It will also increase the time required for a CI run; we may want to set up a separate lane for integration tests / unit tests.

CI: Create an Android pod using Redroid

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.CustomResourceDefinition.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.MobileDevice.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.MobileDevice.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/Polyfill/IKubernetesProtocol.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
src/Kaponata.Operator/Kubernetes/Polyfill/WatchEventDelegate.cs

Use `WatchEventDelegate<T>` instead of `Func<WatchEventType, T, Task<WatchResult>>`

KubernetesProtocol, KubernetesClient: Simplify Watch signatures

---

.github/workflows/build.yaml
ci/redroid.yaml
src/Kaponata.Operator.Tests/Kubernetes/KubernetesServiceCollectionExtensionsTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesServiceCollectionExtensions.cs
src/Kaponata.Operator/Models/MobileDevice.yaml
src/Kaponata.Operator/Program.cs

- Use a helper method for injecting the Kubernetes services into a service container
- Limit CPU and memory usage for the Android container
- Print the labels of the MobileDevice object

Add helper methods for injecting Kubernetes services, minor fixes

---

.github/workflows/website.yaml
website/docs/class/.gitignore
website/docs/class/index.md
website/mkdocs.yml

Use [xmldocmd](https://ejball.com/XmlDocMarkdown/) to convert XML documention to Markdown, and include it in the Kaponata website in the Reference section.

Generate documentation for Kaponata.iOS, Kaponata.Android

---

.github/workflows/images.yaml

Only trigger CI for the container images when the source code changes.

Build iproxy, usbmuxd and adb when needed

---

src/Kaponata.Api.Tests/WebDriver/WebDriverDataTests.cs
src/Kaponata.Api.Tests/WebDriver/WebDriverErrorCodeTests.cs
src/Kaponata.Api.Tests/WebDriver/WebDriverErrorResultTests.cs
src/Kaponata.Api.Tests/WebDriver/WebDriverResultTests.cs
src/Kaponata.Api.Tests/WebDriverControllerTests.cs
src/Kaponata.Api/Startup.cs
src/Kaponata.Api/WebDriver/WebDriverData.cs
src/Kaponata.Api/WebDriver/WebDriverErrorCode.cs
src/Kaponata.Api/WebDriver/WebDriverErrorData.cs
src/Kaponata.Api/WebDriver/WebDriverErrorResult.cs
src/Kaponata.Api/WebDriver/WebDriverResult.cs
src/Kaponata.Api/WebDriver/WebDriverStatus.cs
src/Kaponata.Api/WebDriverController.cs

This PR adds the following endpoints to the API server:
- `GET /wd/hub/status`
- `POST /wd/hub/session`
- `DELETE /wd/hub/session`
The new session and delete session commands always return an error; the main goal of this PR is to add the infrastructure required to handle WebDriver requests to the API server.

API server: Add primary endpoints

---

.github/workflows/build.yaml

https://ci.kaponata.io/ sits behind a CDN network, meaning the content is cached and you may get outdated results when a PR is updated.
A CDN was used because that's the only way to get SSL certificates on custom domains for websites hosted on Azure blob storage.
Replace the URL with https://kaponataci.z6.web.core.windows.net, which is the direct blob storage endpoint.

Fix URL in code coverage report

---

src/Kaponata.Operator.Tests/Kubernetes/KindMetadataTests.cs
src/Kaponata.Operator/Kubernetes/KindMetadata.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.MobileDevice.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Operator/Models/MobileDevice.cs

The methods in the `KubernetesClient` class which operate on `MobileDevice` object contain a fair amount of boilerplate code.
In preparation of the addition of the `WebDriverSession` custom resource definition, this PR moves the boilerplate code to generic methods, which can then be reused across object types.

KubernetesClient: Move generic code to KubernetesClient.NamespacedObject

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.MobileDevice.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.WebDriverSession.cs
src/Kaponata.Operator.Tests/Models/ModelDefinitionsTests.cs
src/Kaponata.Operator/ExtensionsInstaller.cs
src/Kaponata.Operator/Kaponata.Operator.csproj
src/Kaponata.Operator/Kubernetes/KubernetesClient.WebDriverSession.cs
src/Kaponata.Operator/Models/ModelDefinitions.cs
src/Kaponata.Operator/Models/WebDriverSession.cs
src/Kaponata.Operator/Models/WebDriverSession.yaml
src/Kaponata.Operator/Models/WebDriverSessionList.cs
src/Kaponata.Operator/Models/WebDriverSessionSpec.cs
src/Kaponata.Operator/Models/WebDriverSessionStatus.cs

The `WebDriverSession` object will be used to handle user requests to start a new WebDriverSession.
- The API server creates these objects when the user requests a new session
- Operators are responsible for actually creating the WebDriver session
- Ingress rules will forward the session traffic to the pod hosting the session
- The API server deletes the session object, and the Operator deletes the session infrastructure

Add WebDriverSesssion custom resource definition

---

src/Kaponata.Operator.Tests/Kubernetes/FieldSelectorTests.cs
src/Kaponata.Operator.Tests/Kubernetes/LabelSelectorTests.cs
src/Kaponata.Operator/Kubernetes/FieldSelector.cs
src/Kaponata.Operator/Kubernetes/LabelSelector.cs

This PR supports using lambda expressions for defining field selectors and label selectors.
For example, you could express the label selector `kubernetes.io/os=android,kubernetes.io/arch=arm64,app.kubernetes.io/managed-by=my-operator` as:
```csharp
LabelSelector.Create<V1Pod>(
p => p.Metadata.Labels[Annotations.Os] == Annotations.OperatingSystem.Android
&& p.Metadata.Labels[Annotations.Arch] == Annotations.Architecture.Arm64
&& p.Metadata.Labels[Annotations.ManagedBy] == "my-operator")
```
And the field selector `.status.phase=Running` as:
```csharp
FieldSelector.Create<V1Pod>(p => p.Status.Phase == "Running")
```
The main reason for doing is to provide some level of type safety.

Support expression field selectors and label selectors as lambda expressions

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.MobileDevice.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.WebDriverSession.cs
src/Kaponata.Operator.Tests/Operators/KubernetesClientMockExtensions.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Delete.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.WebDriverSession.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Operator/Models/ItemList.cs
src/Kaponata.Operator/Models/MobileDeviceList.cs
src/Kaponata.Operator/Models/WebDriverSessionList.cs

The `KubernetesClient` methods for working with `Pods`, `WebDriverSession` and `MobileDevice` objects have _a lot_ of code in common.
This PR attempts to consolidate the implementations even further by creating a `NamespacedKubernetesClient<T>` class which allows you to interact with namespaced objects of any type.
This client needs to know the Group, Version and Kind ("GVK") information of type `T` to be able to construct the URLs, so that information is passed to its constructor.
It also helps making Kubernetes code more generic. For example, if you were to write code that lists pods or services, you'd need something like this:
```csharp
var podList = kubernetes.ListNamespacedV1PodAsync(....)
var serviceList = kubernetes.ListNamespacedV1ServiceAsync(...)
``` 
meaning you cannot write …

Add a generic NamespacedKubernetesClient<T>

---

.github/workflows/build.yaml
src/Kaponata.Api/Dockerfile
src/Kaponata.Api/Makefile
src/Kaponata.Operator/Dockerfile
src/Kaponata.Operator/Makefile

Publish images to quay.io when building from master, with expiry set to 2 weeks.

Publish container images to quay from master

---

src/Kaponata.Operator.Tests/Kubernetes/LabelSelectorTests.cs
src/Kaponata.Operator/Kubernetes/LabelSelector.cs

There was a hard-coded assumption that the objects passed to the label selector are Pod objects; that's not always true.
Update the assumption to just depend on `IKubernetesObject<V1ObjectMeta>` instead.

Label Selector: Accept any Kubernetes object, not just pods

---

src/Kaponata.Operator.Tests/Kubernetes/NamespacedKubernetesClientTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Delete.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Operator/Kubernetes/NamespacedKubernetesClient.cs

When writing integration tests, it's often useful to make sure the objects which are created during the test do not exist.
While integration tests should clean up after themselves, they may sometimes fail to do so, and this should not impact the next test run.

NamespaceKubernetesClient: Add TryDeleteAsync method

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/CoreApiHandlerTests.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/Polyfill/CoreApiHandler.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.cs

The `NamespacedKubernetesClient<T>` allows you to fetch any type of Kubernetes object in a generic way.
But when you create it for "core" types (like `V1Pod` objects), it will construct the request URL as `/apis/core/v1` instead of `/api/v1`. This is because the "core" API is special, and the KubernetesClient does not know about the core API.
This PR adds a request handler which rewrites the URL so that this scenario works.
Covered by a unit test and an integration test.

KubernetesClient: Fix handling of objects in the "core" namespace

---

src/Directory.Build.props
src/Kaponata.Operator.Tests/Operators/ChildOperatorConfigurationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/KubernetesClientMockExtensions.cs
src/Kaponata.Operator.Tests/Operators/NamespacedKubernetesClientExtensions.cs
src/Kaponata.Operator/Kubernetes/Annotations.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/ChildOperatorConfiguration.cs
src/xunit.runner.json

This `ChildOperator` is intended to be a generic operator which watches for objects and creates 'child' (or dependent) objects when new objects are created.
For example, when a `WebDriverSession` object with `automationType = fake` is created, a `ChildOperator` can be used to create a new `V1Pod` which hosts the fake driver.

Add the ChildOperator operator

---

.github/workflows/build.yaml

The GPG key for Yarn is being renewed, but the GitHub runner images have not been updated. See https://github.com/yarnpkg/yarn/issues/7866

Update Yarn key

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.Pods.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs

This method returns a `HttpClient` which you can use to interact with HTTP services running on the pod.

Add KubernetesClient.CreatePodHttpClient

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator/Operators/ChildOperator.cs

Feedback loops kick in whenever the ChildOperator detects a change in either the parent or child.
They can inspect the state of the parent and child object, and return a JSON patch (or `null`) which updates the parent with information from the child.
Examples of feedback loops are:
- When the WebDriverSession.Status.SessionId value is `null` and the pod which hosts the driver for that session is ready, create a new session and update the SessionId value
- Set the Phase of the WebDriverSession to Initializing when the pod which hosts the driver for that session is being created

ChildOperator: Add support for feedback loops

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorBuilderTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent,TChild}.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent}.cs

For example:
```csharp
var @operator = builder
.CreateOperator("my-operator")
.Watches<WebDriverSession>()
.WithLabels((session) => session.Metadata.Annotations[Annotations.AutomationName] == Annotations.AutomationNames.Fake)
.Where((session) => session.Status?.SessionId == null)
.Creates<V1Pod>((session, pod) =>
{
pod.Spec = new V1PodSpec()
{
Containers = new V1Container[]
{
new V1Container()
{
Image = "quay.io/kaponata/fake-driver:2.0.1",
},
},
};
})
.PostsFeedback((context, cancellationToken) =>
{
var session = context.Parent;
var pod = context.Child;
JsonPatchDocument<WebDriverSession> patch;
if (session.Status?.SessionId != null)
{
patch = null;
}
else if (pod.Status.Phase != "Running" || !pod.Status.ContainerStatuses.All(c => c.Ready))
{
patch = null;
}
else
{
patch = new …
```

Child Operator: Add fluent API for building and configuring child operators.

---

src/Kaponata.Operator.Tests/Kubernetes/NamespacedKubernetesClientTests.cs
src/Kaponata.Operator/Kubernetes/NamespacedKubernetesClient.cs

The `ParentChildOperator`, for example, may want to frequently look up values based on the name (which is used to map parents to children and vice versa), as well as label selectors, which are used to limit the scope of objects on which the operator can act.

NamespacedKubernetesClient.TryReadAsync: Add overload which accepts a label selector

---

src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.Pods.cs

For example, the integration test for `KubernetsClient.CreatePodHttpClient` will attempt to connect to a port on a pod running nginx. These attempts will only succeed if nginx is ready, so have `IsPodRunning` return `true` only if all containers in the pod are considered to be ready.

Pod.IsRunning: Only consider a pod to be running when all containers are ready.

---

src/Kaponata.Operator/Models/WebDriverSession.yaml
src/Kaponata.Operator/Models/WebDriverSessionStatus.cs

This PR adds the `WebDriverSession.Status.SessionReady`, `WebDriverSession.Status.ServiceReady` and `WebDriverSession.Status.IngressReady` fields.
The operators which take care of provisioning the sesssion, service and ingress populate these fields when they have completed.
Obeservers can use these fields to determine whether the session is ready (it is when all three fields are `true`).

WebDriverSession: Add Session, Ingress and Service status fields

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorBuilderTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesClient.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent,TChild}.cs
src/Kaponata.Operator/Operators/ChildOperatorContext.cs
src/Kaponata.Operator/Operators/FeedbackLoop.cs

- Move FeedbackLoop delegate to its own file
- Move ChildOperatorContext to its own file, convert class to struct

Minor ChildOperator refactorings

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator/Kubernetes/Annotations.cs
src/Kaponata.Operator/Operators/ChildOperator.cs

The operator consists roughly of three concurrent tasks:
- Two watch tasks (one for parents and one for children), which detect changes to parents & children and schedule reconciliation whenever a change is detected
- A task which performs all reconciliations
The current implementation has the watch tasks post the state _at the moment the watch event is processed_ to the reconciliation queue.
If two events (e.g. an Added and a Modified event) come in shortly after each other, it is possible for the same (or similar) state to be pushed twice to the reconciliation queue, after which the reconcilation task will request the same change to be made. This results in a conflict.
This PR updates the reconciliation queue to consist only of the name of the parent/child pair to be reconciled. The …

ChildOperator: Have reconcilation be done based on name, not specific objects

---

src/fake-driver/Dockerfile

By default, the fake driver will listen on `127.0.0.1`, which means the port is not accessible externally. Pass `--host 0.0.0.0` so the port is accessible via the cluster network.

fake-driver: List on all addresses, not just localhost

---

src/fake-driver/Dockerfile

This should help get us a fast and smooth shutdown of the fake driver pod.

fake-driver: use tini init system

---

src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
src/Kaponata.Operator.Tests/Kubernetes/Polyfill/StreamReaderExtensionsTests.cs
src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
src/Kaponata.Operator/Kubernetes/Polyfill/StreamReaderExtensions.cs

Currently, when a Watch operation is cancelled, the HttpResponse is disposed off. This causes an IOException in `ReadLineAsync`.
Avoid this exception by adding an `ReadLineAsync(cancellationToken)` instead, which will return `null` when a cancellation is requested.

Watcher: Support exceptionless cancellations

---

src/adb/Makefile
src/fake-driver/Makefile
src/iproxy/Makefile
src/usbmuxd/Makefile

Running `make push` repeatedly in scenarios where the manifest tag did not change (not a best practice but something which happens during test cycles) would result in the `latest-amd64` and `latest-arm64` being updated on the registry, but the remote manifest itself would still point to older images.
Add a `docker manifest rm` to work around this.

Avoid stale manifests by re-creating them

---

src/Kaponata.Kubernetes/FieldSelector.cs
src/Kaponata.Kubernetes/Kaponata.Kubernetes.csproj
src/Kaponata.Kubernetes/KubernetesClient.Crd.cs
src/Kaponata.Kubernetes/KubernetesClient.Delete.cs
src/Kaponata.Kubernetes/KubernetesClient.MobileDevice.cs
src/Kaponata.Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Kubernetes/KubernetesClient.WebDriverSession.cs
src/Kaponata.Kubernetes/KubernetesClient.cs
src/Kaponata.Kubernetes/LabelSelector.cs
src/Kaponata.Kubernetes/Models/ItemList.cs
src/Kaponata.Kubernetes/Models/MobileDevice.cs
src/Kaponata.Kubernetes/Models/MobileDeviceSpec.cs
src/Kaponata.Kubernetes/Models/MobileDeviceStatus.cs
src/Kaponata.Kubernetes/Models/ModelDefinitions.cs
src/Kaponata.Kubernetes/Models/WebDriverSession.cs
src/Kaponata.Kubernetes/Models/WebDriverSessionSpec.cs
src/Kaponata.Kubernetes/Models/WebDriverSessionStatus.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Kubernetes/Polyfill/CoreApiHandler.cs
src/Kaponata.Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
src/Kaponata.Kubernetes/Polyfill/ListNamespacedObjectWithHttpMessagesAsyncDelegate.cs
src/Kaponata.Kubernetes/Polyfill/StreamReaderExtensions.cs
src/Kaponata.Kubernetes/Polyfill/WatchHandler.cs
src/Kaponata.Kubernetes/Polyfill/WatchHttpContent.cs
src/Kaponata.Kubernetes/Selector.cs

Notable exceptions are:
- Kubernetes models: Nullable annotations are disabled (in line with upstream KubernetesClient)
- LabelSelector and FieldSelector classes: annotations are disabled

Kaponata.Kubernetes: Enable nullable annotations

---

src/Kaponata.Chart.Tests/ApiTests.cs
src/Kaponata.Chart.Tests/OperatorTests.cs
src/Kaponata.Chart.Tests/UsbmuxdTests.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientIntegrationTests.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.CustomResourceDefinition.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.MobileDevice.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.Pods.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.WebDriverSession.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.cs
src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientTests.cs
src/Kaponata.Kubernetes/KubernetesClient.MobileDevice.cs
src/Kaponata.Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Kubernetes/KubernetesClient.WebDriverSession.cs
src/Kaponata.Kubernetes/KubernetesClient.cs
src/Kaponata.Kubernetes/KubernetesOptions.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Kubernetes/Polyfill/KubernetesProtocol.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Service.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/KubernetesClientMockExtensions.cs
src/Kaponata.Operator.Tests/Operators/NamespacedKubernetesClientExtensions.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/ChildOperatorConfiguration.cs
src/Kaponata.Operator/Operators/RedroidOperator.cs

Make the Kubernetes namespace in which to operate an option of the `KubernetesClient`, instead of an argument to all methods.
Kaponata will always operate in a well-defined namespace, so make this a one-off configuration option.
Plus, unit tests in #114 are failing because they are interfering with the operation which is deployed via the Helm chart. Making this an option will help us isolate the unit tests in a dedicated namespace.

Make the Kubernetes namespace in which to operate an option

---

.github/workflows/build.yaml
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.MobileDevice.cs
src/Kaponata.Kubernetes.Tests/KubernetesServiceCollectionExtensionsTests.cs
src/Kaponata.Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Kubernetes/KubernetesServiceCollectionExtensions.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorBuilderTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Service.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent,TChild}.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent}.cs
src/Kaponata.Operator/Operators/FakeOperatorExtensions.cs
src/Kaponata.Operator/Operators/FakeOperators.cs
src/Kaponata.Operator/Startup.cs
src/chart/templates/operator-role.yaml

This PR enables the fake operator by default, as part of the `Kaponata.Operator` project.
This means `Kaponata.Operator` now hosts the `RedroidOperator` and the `FakeOperator` infrastructure.
We may want to split this project into multiple, smaller projects when this project starts hosting multiple operators.
For this to work:
- There's a `AddFakeOperators(this IServiceCollection services)` extension method which allows you to add the fake operators to a service collection
- The various methods for building operators now operate on `IServiceProvider` instead of `IHost` to support the above extension method.
As a separate commit, this PR also grants the operator pod CRUD permissions to the `WebDriverSession` and `MobileDevice` objects.

Fake Operator: Enable by default

---

src/Kaponata.Api.Tests/Kaponata.Api.Tests.csproj
src/Kaponata.Api.Tests/KubernetesWebDriverTests.cs
src/Kaponata.Api/Kaponata.Api.csproj
src/Kaponata.Api/KubernetesWebDriver.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Operator.Tests/Kaponata.Operator.Tests.csproj
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Tests.Shared/NamespacedKubernetesClientExtensions.cs

The `KubernetesWebDriver` class is responsible for creating WebDriver sessions by creating a `WebDriverSession` object in the Kubernetes cluster, and report back whether the session has been provisioned successfully.
Once this PR is merged, the `WebDriverController` can be updated to invoke the `KubernetesWebDriver` class, rather than just returning error codes.

 Add the KubernetesWebDriver class

---

src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator/Operators/FakeOperators.cs

`CreateFakeSession_IntegrationTest_Async` seems to be particularly flakey because the session is considered to be "ready" even though the reverse proxy rules have not yet been deployed.

Fake operator: Set ingress to true only if a load balancer has been assigned.

---

src/Kaponata.Api.Tests/KubernetesWebDriverIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorIntegrationTests.cs

They will interfere with each other.

Prevent operator tests from running in parallel

---

src/Kaponata.Api.Tests/WebDriverControllerTests.cs
src/Kaponata.Api/KubernetesWebDriver.cs
src/Kaponata.Api/WebDriverController.cs

This updates the `WebDriverController` to call the `KubernetesWebDriver` to perform the session creation/deletion.
The actual session requests are forwarded to the backend via the ingress rules.

WebDriver: Implement session creation

---

src/Kaponata.Kubernetes.Tests/KubernetesObjectExtensionsTests.cs
src/Kaponata.Kubernetes/KubernetesObjectExtensions.cs
src/Kaponata.Operator/Operators/ChildOperator.cs

Instead of manually creating the `V1OwnerReference` object over and over again, add an extension method for this.

Add IKubernetesObject.AsOwnerReference extension method

---

src/Kaponata.Kubernetes.Tests/KindMetadataTests.cs
src/Kaponata.Kubernetes.Tests/KubernetesClientTests.NamespacedObject.cs
src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientTests.cs
src/Kaponata.Kubernetes/KindMetadata.cs
src/Kaponata.Kubernetes/KubernetesClient.cs
src/Kaponata.Kubernetes/Models/MobileDevice.cs
src/Kaponata.Kubernetes/Models/WebDriverSession.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs

Have `TryReadAsync` also populates the `ApiGroup` and `Kind` properties on the individual items. This acts as a workaround for https://github.com/kubernetes/kubernetes/issues/80609, https://github.com/kubernetes/kubernetes/issues/3030 and https://github.com/kubernetes/kubernetes/pull/80618

NamespacedKubernetesClient.TryReadAsync: Always populate the ApiGroup, Kind properties

---

ci/redroid.yaml

The Redroid container is a bit finicky. If the kernel modules are not loaded properly (the binder in particular), the container will launch but never enter the ready state.
Add init containers which perform very simple startup health checks to fail-fast and prevent the container from booting.

Redroid: Add readiness checks

---

src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Operator.Tests/LogConfig.cs
src/Kaponata.Operator.Tests/LogFormatter.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/RedroidOperatorTests.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/RedroidOperator.cs
src/Kaponata.Operator/Startup.cs
src/Kaponata.Tests.Shared/NamespacedKubernetesClientExtensions.cs

This PR rewrites the `RedroidOperator` as a `ChildOperator`, and manages to remove a bunch of code in the process.
It also updates the `ci/redroid.yaml` file to include some init containers, which prevent the Redroid container from booting if the required modules (`ashmem_linux` and `binder_linux`) are not configured properly.

RedroidOperator: Rewrite as an a ChildOperator

---

.github/workflows/images.yaml
src/adb/Dockerfile
src/appium-android/Dockerfile
src/appium-android/Makefile
src/appium/Dockerfile

This PR adds the kaponata/appium-android image, which builds on the kaponata/appium image, and adds the ADK-specific tools required by the appium-android-uiautomator2 image.
Specifically, this adds:
- adb
- apksigner.jar
The apksigner.jar is a Java application, so this adds a dependency on a Java runtime, too. In the current iteration, this uses OpenJDK.
Installing the ADK is always a bit of an adventure. Installing the utilities via the cmdline-tool package would pull in all sorts of dependencies (including the emulator), so the strategy for now is to download the individual zip files and extract them.
To reduce the size of the final container, only tools which are required (as opposed to all those available in the ADK) are copied to the container.
This PR also:
- Fixes the …

Add the kaponata/appium-android image

---

src/adb/Makefile
src/appium-android/Makefile
src/appium/Makefile
src/fake-driver/Makefile
src/iproxy/Makefile
src/usbmuxd/Makefile

For example, no terminal is available when building the Docker images in GitHub pipelines.

Don't attach an terminal when none may be available

---

ci/appium.yaml
ci/capabilities.json
ci/redroid.sh
ci/redroid.yaml

This PR:
- Updates the Redroid YAML file to use Redroid 10.0, as we've seen some issues with Redroid 11 (to be confirmed)
- Adds a YAML file for hosting an Appium pod which can run tests on Android devices. It hosts both the Appium server and an instance of the adb server.

Sample YAML files for starting Appium on Redroid

---

src/adb/Dockerfile
src/appium-android/Dockerfile

- Terminating a container where adb is running as the top-level process does not work correctly; use tini for signal handling
- Use platform-tools 31.0.0 in the adb and appium-android containers
- Add missing NOTICE files

adb: use tini, bump to 31.0.0

---

src/Kaponata.Kubernetes/Models/WebDriverSession.yaml
src/Kaponata.Kubernetes/Models/WebDriverSessionSpec.cs
src/Kaponata.Kubernetes/Models/WebDriverSessionStatus.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Service.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.cs
src/Kaponata.Operator/Operators/FakeOperators.cs

This PR updates the WebDriverSession objects:
- Adds a `spec.deviceHost` field, which should store the IP address at which the muxer/daemon for the device can be reached (think adbd, adb or usbmuxd)
- Adds a `status.sessionPort` field, which contains the TCP port at which the Appium server is running. Not all servers use the same port (think fake-driver vs Appium), so make it configurable
It also updates the ingress and service operators to repsect the `sessionPort` value.

WebDriverSession: Add deviceHost, sessionPort fields

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Service.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilder{TParent,TChild}.cs
src/Kaponata.Operator/Operators/ChildOperatorContext.cs

An operator may want to access various services in its reconciliation loop.
For example, when working with Android devices, the feedback loop may want to create an `AdbClient` instance so that it can connect to the Android device and configure the device.
This PR:
- Extends the `ChildOperatorContext<TParent, TChild>` class so that it has a `Services` property, which exposes the ServiceProvider.
- Updates the `ChildOperator<TParent, TChild>` class to pass a new service scope to the operator context

ChildOperator: Expose the current service provider as part of the operator context.

---

src/Kaponata.Android.Tests/Adb/AdbClientTests.cs
src/Kaponata.Android/Adb/AdbClient.Services.cs
src/Kaponata.Android/Adb/AdbClient.cs
src/Kaponata.Android/Adb/AdbProtocol.cs

- `AdbClient`: add a protected parameterless constructor which can be used for mocking purposes
- Add a unit test which makes sure that an `AdbClient` can be configured in DI, and that it uses a `AdbSocketLocator` 
- `AdbClient`: mark some methods as `virtual` so they can be mocked
- `AdbClientProtocol`: Expose the underlying stream as property, so we can check it's operating on the correct base stream.

AdbClient: Better support for mocking, DI

---

src/Kaponata.Kubernetes/Annotations.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesAdbContextTests.cs
src/Kaponata.Operator.Tests/Kubernetes/KubernetesAdbSocketLocatorTests.cs
src/Kaponata.Operator.Tests/Operators/UIAutomatorOperatorsTests.cs
src/Kaponata.Operator/Kubernetes/KubernetesAdbContext.cs
src/Kaponata.Operator/Kubernetes/KubernetesAdbSocketLocator.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilderExtensions.cs
src/Kaponata.Operator/Operators/SessionPodInitializer.cs
src/Kaponata.Operator/Operators/UIAutomatorOperators.cs

This operator supports creating Appium sessions which run Appium on Android devices using the UIAutomator2 provider.
The operator:
- Creates an Appium pod which runs Appium in a container and adb in another
- Has a feedback loop which calls `adb.Connect("...")` to connect that adb instance to the device

Add UIAutomatorOperator

---

.github/workflows/images.yaml
src/guacamole/Dockerfile
src/guacamole/Makefile
src/guacamole/guacamole.properties

This image contains the guacamole-auth-rest extension.
This enables configuring Guacamole using a REST API.

Add Guacamole Docker image

---

src/Kaponata.Operator.Tests/Operators/ChildOperatorBuilderTests.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Ingress.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.Service.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorTests.cs
src/Kaponata.Operator.Tests/Operators/UIAutomatorOperatorsTests.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Operator/Operators/ChildOperatorBuilderExtensions.cs
src/Kaponata.Operator/Operators/FakeOperators.cs
src/Kaponata.Operator/Operators/Feedback.cs
src/Kaponata.Operator/Operators/FeedbackLoop.cs

So far, the operators supported on-way feedback (from the child to the parent).
This PR adds two-way feedback, so that the child can also react to status changes in the parent.
For example, consider the Redroid operator, which creates `MobileDevice` objects for redroid pods.
If the pod is restarted or otherwise changes the IP address, the IP field of the `MobileDevice` object will need to be updated too (unless we create a service object in between).

Operator: Support two-way feedback

---

src/chart/templates/_helpers.tpl
src/chart/templates/api-role.yaml
src/chart/templates/api-roleBinding.yaml

The API server will enumerate all mobile device objects and expose the VNC configuration to the Guacamole server, so it needs to access these mobile device objects.

Grant API server list, get permissions on mobiledevice objects

---

.github/workflows/build.yaml
src/Kaponata.Api.Tests/GuacamoleControllerTests.cs
src/Kaponata.Api/GuacamoleController.cs
src/Kaponata.Api/Startup.cs

Update the GuacamoleController to actually return Connection objects for each MobileDevice which has an active VNC host.

GuacamoleController: Add configurations for MobileDevice objects

---

src/Kaponata.Api.Tests/GuacamoleControllerTests.cs
src/Kaponata.Api/GuacamoleController.cs

Guacamole uses lower-case spellings of protocol names.

GuacamoleController: Fix spelling of "vnc"

---

src/Kaponata.Api/Makefile
src/Kaponata.Operator/Makefile

For some reason, the `-name "*.cs"` filter does not work when using Make on native Windows (e.g. _not_ WSL), but the `-regex '.*\.cs'` filter does work.
This PR replaces the filter. With this change, you can now run commands such as `make deploy` from a Windows command-line prompt, if you have `make`, `find`, `kubectl`, `k3d`, `docker` and `docker-buildx` available in your PATH.

Update Makefiles to be Windows/PowerShell compatible

---

.github/workflows/build.yaml
src/Kaponata.Kubernetes.Tests/LabelSelectorTests.cs
src/Kaponata.Kubernetes/LabelSelector.cs
src/Kaponata.Sidecars.Tests/Kaponata.Sidecars.Tests.csproj
src/Kaponata.Sidecars/Dockerfile
src/Kaponata.Sidecars/Kaponata.Sidecars.csproj
src/Kaponata.Sidecars/Makefile
src/Kaponata.Sidecars/Program.cs
src/Kaponata.sln

The sidecars will be used to publish `MobileDevice` objects into the Kubernetes cluster, based on devices available in `usbmuxd`.
This PR scaffolds the sidecars project and publishes the container to the quay registry.

Scaffold Kaponata.Sidecar project

---

.github/workflows/build.yaml
src/Kaponata.Chart.Tests/UsbmuxdTests.cs
src/Kaponata.Sidecars/Program.cs
src/chart/charts/usbmuxd/templates/_helpers.tpl
src/chart/charts/usbmuxd/templates/daemonset.yaml
src/chart/charts/usbmuxd/templates/usbmuxd-role.yaml
src/chart/charts/usbmuxd/templates/usbmuxd-roleBinding.yaml
src/chart/charts/usbmuxd/templates/usbmuxd-serviceAccount.yaml
src/chart/charts/usbmuxd/values.yaml

This adds the sidecar to the usbmuxd pod, and grants the usbmuxd pod CRUD permissions on mobiledevice objects and permissions to get/list pods (this allows the pod to find its own identity, which is used to set the ownership on the mobiledevice object).

Add sidecar to usbmuxd pod

---

.github/workflows/build.yaml
src/Kaponata.Chart.Tests/GuacamoleTests.cs
src/Kaponata.Kubernetes.Tests/DeveloperProfiles/KubernetesDeveloperProfileTests.ProvisioningProfile.cs
src/Kaponata.Kubernetes.Tests/DeveloperProfiles/KubernetesDeveloperProfileTests.X509Certificate2.cs
src/Kaponata.Kubernetes.Tests/DeveloperProfiles/KubernetesDeveloperProfileTests.cs
src/Kaponata.Kubernetes/Annotations.cs
src/Kaponata.Kubernetes/DeveloperProfiles/KubernetesDeveloperProfile.ProvisioningProfile.cs
src/Kaponata.Kubernetes/DeveloperProfiles/KubernetesDeveloperProfile.X509Certificate2.cs
src/Kaponata.Kubernetes/DeveloperProfiles/KubernetesDeveloperProfile.cs
src/Kaponata.Kubernetes/KubernetesClient.cs
src/chart/charts/guacamole/templates/guacamole-deployment.yaml

This commit introduces the KubernetesDeveloperProfile as a class
for interacting with developer profile components (certificates and
provisioning profiles) stored in a Kubernetes cluster.

Store iOS development identities, provisioning profiles in Kubernetes using secrets

---

ci/kaponata/Vagrantfile
ci/kaponata/playbook.yml
init.ps1
src/Kaponata.Api/Makefile
src/Kaponata.Operator/Makefile
src/Kaponata.Sidecars/Makefile
src/Makefile
src/usbmuxd/Makefile

The Vagrant box was using k3d (k3s-in-docker) to provision k3s. As a result, pods run
inside containerd inside Docker. A limitation of this setup is that usb
hotplug does not work correctly: newly attached devices are not discoverable
inside the container.
This PR reworks the Vagrant setup to use "native" k3s, and forces k3s to use
Docker as the container runtime (simplifying the setup a bit).

Vagrant box: Use k3s instead of k3d

---

src/Kaponata.Kubernetes.Tests/PortForwardStreamTests.cs
src/Kaponata.Kubernetes/PortForwardStream.cs

Zero-length packets may be used to signal the remote end has
closed the connection. Correctly handle this case.

PortForwardStream: Handle zero-length packets

---

src/Kaponata.Chart.Tests/UsbmuxdTests.cs
src/chart/Makefile
src/chart/charts/usbmuxd/templates/_helpers.tpl
src/chart/charts/usbmuxd/templates/daemonset.yaml
src/chart/charts/usbmuxd/templates/usbmuxd-configMap.yaml

Use a ConfigMap to store the `/var/lib/lockdown/SystemConfiguration.plist`
configuration file, so that all usbmuxd instances return the same SystemBUID value.

usbmuxd: Use a global SystemBUID value

---

src/usbmuxd/Dockerfile.template
src/usbmuxd/Makefile

The usbmuxd sidecar will take care of creating the pairing
records for iOS devices (and store them in the Kubernetes cluster).
As a result, we can skip the dependency on libimobiledevice
and reduce the overall container size.

usbmuxd: Skip preflight

---

src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS.Tests/Lockdown/StartSessionRequestTests.cs
src/Kaponata.iOS.Tests/Lockdown/StartSessionResponseTests.cs
src/Kaponata.iOS.Tests/Lockdown/StopSessionRequestTests.cs
src/Kaponata.iOS/Lockdown/LockdownClient.Session.cs
src/Kaponata.iOS/Lockdown/StartSessionRequest.cs
src/Kaponata.iOS/Lockdown/StartSessionResponse.cs
src/Kaponata.iOS/Lockdown/StopSessionRequest.cs

At the moment without support for enabling session SSL.

LockdownClient: Add StartSession/StopSession support

---

src/Kaponata.iOS.Tests/Muxer/DeletePairingRecordMessageTests.cs
src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.PairingRecords.cs
src/Kaponata.iOS/Muxer/DeletePairingRecordMessage.cs
src/Kaponata.iOS/Muxer/MuxerClient.PairingRecord.cs
src/Kaponata.iOS/Muxer/MuxerMessageType.cs

Supports deleting pair records stored on the server.

Add MuxerClient.DeletePairingRecordAsync

---

src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.PairingRecords.cs
src/Kaponata.iOS.Tests/Muxer/MuxerPairingRecordStoreTests.cs
src/Kaponata.iOS/Lockdown/PairingRecordStore.cs
src/Kaponata.iOS/Muxer/MuxerClient.PairingRecord.cs
src/Kaponata.iOS/Muxer/MuxerPairingRecordStore.cs

This class can serve as a base class for classes which provide access
to a repository in which pairing records can be stored, such as
an usbmuxd instance (part of this PR) or a Kubernetes cluster
(part of a follow-up PR).

Add the PairingRecordStore

---

src/Kaponata.Kubernetes.Tests/PairingRecords/KubernetesPairingRecordStoreIntegrationTests.cs
src/Kaponata.Kubernetes.Tests/PairingRecords/KubernetesPairingRecordStoreTests.cs
src/Kaponata.Kubernetes.Tests/PairingRecords/V1SecretExtensionsTests.cs
src/Kaponata.Kubernetes/PairingRecords/KubernetesPairingRecordStore.cs
src/Kaponata.Kubernetes/PairingRecords/V1SecretExtensions.PairingRecord.cs

This enables storing pairing records in a Kubernetes cluster, as opposed to locally.

Add the KubernetesPairingRecordsStore

---

src/Kaponata.iOS.Tests/Lockdown/PairingRecordGeneratorTests.cs
src/Kaponata.iOS/Lockdown/PairingRecordGenerator.cs

Attempting to pair with a device when `HostID` has lowercase characters will result in the pair dialog being displayed on the device, but pairing will fail to complete with a `InvalidPairRecord` error when the user taps the `Trust` button.

PairingRecordGenerator: Make sure that HostID is upper-case

---

src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Pair.cs
src/Kaponata.iOS.Tests/Muxer/PairResponseTests.cs
src/Kaponata.iOS/Lockdown/LockdownClient.Pair.cs
src/Kaponata.iOS/Lockdown/PairResponse.Serialization.cs
src/Kaponata.iOS/Lockdown/PairResponse.cs
src/Kaponata.iOS/Lockdown/PairingResult.cs
src/Kaponata.iOS/Lockdown/PairingStatus.cs

The device will respond with an escrow bag when pairing succeeds; make sure to return this data as well, so that it can be added to the pairing record when needed.

LockdownClient.Pair: Return EscrowBag data, too.

---

src/Kaponata.iOS.Tests/Lockdown/LockdownClientFactoryTests.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.GetValue.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Pair.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.StartService.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownProtocolTests.cs
src/Kaponata.iOS.Tests/NotificationProxy/NotificationProxyClientTests.cs
src/Kaponata.iOS.Tests/PropertyLists/PropertyListProtocolTests.cs
src/Kaponata.iOS/ClientFactory.cs
src/Kaponata.iOS/DeviceContext.cs
src/Kaponata.iOS/Lockdown/LockdownClient.cs
src/Kaponata.iOS/Lockdown/LockdownClientFactory.cs
src/Kaponata.iOS/Lockdown/LockdownProtocol.cs
src/Kaponata.iOS/NotificationProxy/NotificationProxyClient.cs
src/Kaponata.iOS/PropertyLists/PropertyListProtocol.cs

This PR:
- Moves the `static LockdownClient.ConnectAsync` method to a `LockdownClientFactory` class. This should make it easier to mock this method in unit tests.
- Add trace logging to `PropertyListProtocol`, `LockdownClient`.

LockdownClient: Move `ConnectAsync` to a factory class, add logging

---

src/Kaponata.Sidecars.Tests/UsbmuxdSidecarTests.cs
src/Kaponata.Sidecars/UsbmuxdSidecar.cs
src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.cs
src/Kaponata.iOS/Muxer/MuxerClient.Listen.cs

The callbacks are async but currently we don't provide them with a cancellation token. Let's fix that.

MuxerClient: Pass cancellation tokens to callbacks

---

src/Kaponata.iOS.Tests/DependencyInjection/ServiceCollectionExtensionsTests.cs
src/Kaponata.iOS.Tests/DependencyInjection/ServiceProviderExtensionsTests.cs
src/Kaponata.iOS.Tests/GlobalSuppressions.cs
src/Kaponata.iOS/DependencyInjection/ServiceCollectionExtensions.cs
src/Kaponata.iOS/DependencyInjection/ServiceProviderExtensions.cs
src/Kaponata.iOS/GlobalSuppressions.cs
src/Kaponata.iOS/Kaponata.iOS.csproj
src/Kaponata.iOS/NotificationProxy/NotificationProxyClientFactory.cs
src/Kaponata.iOS/ServiceClientFactory.cs

This commit adds the ability to register services which interact with devices via dependency injection. It introduces the concept of a "device scope".
A device scope is a scope in which the DeviceContext service is registered. This service contains the information about the device on which the scope interacts.
You can configure a service collection by calling the `AddAppleServices` method. Once the service provider has been built, you can create a device scope by calling the `CreateDeviceScopeAsync` method.
This method takes a `udid` as a parameter (which can be `null` or a specific UDID).

iOS: Support registering clients via dependency injection

---

src/Kaponata.iOS.Tests/DependencyInjection/DeviceServiceScopeTests.cs
src/Kaponata.iOS.Tests/DependencyInjection/ServiceProviderExtensionsTests.cs
src/Kaponata.iOS.Tests/DependencyInjection/ServiceScopeExtensionsTests.cs
src/Kaponata.iOS/DependencyInjection/DeviceServiceScope.cs
src/Kaponata.iOS/DependencyInjection/ServiceProviderExtensions.cs
src/Kaponata.iOS/DependencyInjection/ServiceScopeExtensions.cs

This commit adds the IServiceProvider.StartServiceAsync<T>(CancellationToken) method which can be used to start a service on an iOS device and connect to that service.
It abstracts away the mechanics of finding the service factory and connecting to the service using the service factory.

Dependency injection: Add convenience methods for starting iOS services.

---

src/usbmuxd/Makefile

awk accesses variables using "$", and this confuses PowerShell on Windows.

usbmuxd: Use 'cut' instead of 'awk'

---

src/Kaponata.iOS.Tests/DependencyInjection/ServiceProviderExtensionsTests.cs
src/Kaponata.iOS.Tests/Kaponata.iOS.Tests.csproj
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS.Tests/PropertyLists/PropertyListProtocolTests.Ssl.cs
src/Kaponata.iOS.Tests/PropertyLists/PropertyListProtocolTests.cs
src/Kaponata.iOS.Tests/PropertyLists/X509Certificate2ExtensionsTests.cs
src/Kaponata.iOS/DependencyInjection/ServiceProviderExtensions.cs
src/Kaponata.iOS/DeviceContext.cs
src/Kaponata.iOS/Lockdown/LockdownClient.Session.cs
src/Kaponata.iOS/PropertyLists/PropertyListProtocol.Ssl.cs
src/Kaponata.iOS/PropertyLists/PropertyListProtocol.cs
src/Kaponata.iOS/PropertyLists/X509Certificate2Extensions.cs

This PR adds support for enabling SSL encryption after staring a lockdown session.
It includes a bit of a workaround on Windows, because certificate authentication on the `SslStream` cannot use ephemeral keys: https://github.com/dotnet/runtime/issues/45680 / https://github.com/dotnet/runtime/issues/23749

LockdownClient: Support SSL encryption

---

src/Kaponata.Chart.Tests/RegistryTests.cs
src/chart/templates/_helpers.tpl
src/chart/templates/registry-service.yaml
src/chart/templates/registry-statefulset.yaml
src/chart/values.yaml

We will store the iOS developer disk images as container images in the Docker registry.
By default, the registry will use "local-path" storage. This is
(non-redundant) cluster-local storage and is enable by default
in k3s clusters.
The registry is deployed as a StatefulSet to ensure the PVC
can be reused after redeploying the same helm chart.
Contributes towards #220

Deploy a Docker registry as part of Kaponata

---

src/Kaponata.FileFormats.Tests/Kaponata.FileFormats.Tests.csproj
src/Kaponata.FileFormats.Tests/Lzma/LzmaStreamTests.cs
src/Kaponata.FileFormats/Lzma/LzmaResult.cs
src/Kaponata.FileFormats/Lzma/LzmaStream.cs
src/Kaponata.FileFormats/Lzma/XZInputStream.cs
src/Kaponata.FileFormats/Lzma/XZOutputStream.cs

- Fix the layout of the `LzmaStream` struct, which would cause random issues on 64-bit platforms.
- Spanify the `XZInputStream` class

XZ fixes: fix struct layout, spanify code

---

src/Kaponata.FileFormats.Tests/Lzma/XZDecompressorTests.cs
src/Kaponata.FileFormats/Lzma/XZDecompressor.cs

Enables decompressing XZ or LZMA-compressed data without the need to construct a stream.
Contributes towards #234

Add the XZDecompressor class

---

src/Kaponata.Kubernetes.Tests/DeveloperDisks/DeveloperDiskRegistryImageFactoryTests.cs
src/Kaponata.Kubernetes.Tests/Registry/DescriptorTests.cs
src/Kaponata.Kubernetes/DeveloperDisks/DeveloperDiskRegistryImageFactory.cs
src/Kaponata.Kubernetes/Registry/Descriptor.cs
src/Kaponata.iOS.Tests/DeveloperDisks/DeveloperDiskReaderTests.cs
src/Kaponata.iOS.Tests/DeveloperDisks/DeveloperDiskTests.cs
src/Kaponata.iOS/DeveloperDisks/DeveloperDisk.cs
src/Kaponata.iOS/DeveloperDisks/DeveloperDiskReader.cs

This container image has the following specifications:
- It contains a single filesystem layer, which contains:
* The developer disk image
* The signature of the developer disk image
* A copy of the `SystemVersion.plist` file
- The manifest has the following annotations:
* BuildID, ProductBuildVersion, ProductName and ProductVersion annotations: copied from SystemVersion.plist
* DeveloperDisk.dmg.signature: The base64-encoded signature of the developer disk.

Support packaging the developer disk as a container image.

---

src/Kaponata.Api.Tests/DeveloperDiskControllerTests.cs
src/Kaponata.Api.Tests/TempFileStreamTests.cs
src/Kaponata.Api/DeveloperDiskController.cs
src/Kaponata.Api/TempFileStream.cs
src/Kaponata.Kubernetes.Tests/DeveloperDisks/RegistryDeveloperDiskStoreTests.cs
src/Kaponata.Kubernetes.Tests/LabelSelectorTests.cs
src/Kaponata.Kubernetes.Tests/Registry/ImageRegistryClientConfigurationTests.cs
src/Kaponata.Kubernetes.Tests/Registry/ImageRegistryClientFactoryTests.cs
src/Kaponata.Kubernetes.Tests/Registry/ImageRegistryExceptionTests.cs
src/Kaponata.Kubernetes/DeveloperDisks/RegistryDeveloperDiskStore.cs
src/Kaponata.Kubernetes/KubernetesClient.cs
src/Kaponata.Kubernetes/KubernetesServiceCollectionExtensions.cs
src/Kaponata.Kubernetes/LabelSelector.cs
src/Kaponata.Kubernetes/Registry/ImageRegistryClient.cs
src/Kaponata.Kubernetes/Registry/ImageRegistryClientConfiguration.cs
src/Kaponata.Kubernetes/Registry/ImageRegistryClientFactory.cs
src/Kaponata.Kubernetes/Registry/ImageRegistryException.cs
src/Kaponata.iOS.Tests/DeveloperDisks/DeveloperDiskFactoryTests.cs
src/Kaponata.iOS.Tests/DeveloperDisks/DeveloperDiskTests.cs
src/Kaponata.iOS/DeveloperDisks/DeveloperDisk.cs
src/Kaponata.iOS/DeveloperDisks/DeveloperDiskFactory.cs

This PR adds the following routes:
| Route | Description |
|-------|----|
| `GET api/ios/developerDisk/` | Lists all developer disks known to Kaponata |
| `POST api/ios/developerDisk/` | Uploads a new developer disk to Kaponata. You need to post a form, which contains two files: `DeveloperDiskImage.dmg` and `DeveloperDiskImage.dmg.signature` |
|  `GET api/ios/developerDisk/{version}/disk` | Dowload the developer disk image | 
| `GET api/ios/developerDisk/{version}/signature` | Download the developer disk signature | 
These routes are backed by the `DeveloperDiskController` controller. The dependencies (`RegistryDeveloperDiskStore` and `ImageRegistryClient`) are injected via dependency injection. This PR introduces a `ImageRegistryClientFactory` class which can create …

Support storing developer disk images in a Kubernetes registry

---

src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.GetValue.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Pair.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.SetValue.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownResponseTests.cs
src/Kaponata.iOS.Tests/PropertyLists/PropertyListProtocolTests.cs
src/Kaponata.iOS/Lockdown/LockdownClient.GetValue.cs
src/Kaponata.iOS/Lockdown/LockdownClient.Session.cs
src/Kaponata.iOS/Lockdown/LockdownClient.SetValue.cs
src/Kaponata.iOS/Lockdown/LockdownClient.cs
src/Kaponata.iOS/Lockdown/LockdownResponse.Serialization.cs
src/Kaponata.iOS/Lockdown/LockdownResponse.cs
src/Kaponata.iOS/PropertyLists/PropertyListProtocol.Ssl.cs
src/Kaponata.iOS/PropertyLists/PropertyListProtocol.cs

- Implement IDisposableVerifiable
- Throw when disposed
- Add convenience ReadMessageAsync<T> where T is IPropertyListDeserializable, to avoid code duplciation

PropertyListProtocol improvements

---

src/Kaponata.FileFormats.Tests/Kaponata.FileFormats.Tests.csproj
src/Kaponata.FileFormats/Kaponata.FileFormats.csproj

The only difference is that this is a "released" version of DiscUtils, and publishing to NuGet of Kaponata.FileFormats should be unblocked.

Bump DiscUtils to 0.16.6

---

src/Kaponata.iOS.Tests/MobileImageMounter/LookupImageResponseTests.cs
src/Kaponata.iOS.Tests/MobileImageMounter/MobileImageMounterClientTests.cs
src/Kaponata.iOS.Tests/MobileImageMounter/MobileImageMounterResponseTests.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterClient.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterError.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterException.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterResponse.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterStatus.cs

Use enum values for the status and error codes returned by the client.

MobileImageMounterClient: Improve error handling

---

src/Kaponata.Kubernetes.Tests/Registry/ImageRegistryClientTests.cs
src/Kaponata.Kubernetes/Registry/ImageRegistryClient.cs

This avoid having to catch an error to determine whether the manifest exists or not.

ImageRegistryClient.GetManifestAsync: Return null when not found

---

src/Kaponata.Sidecars.Tests/PairingRecordProvisionerTests.cs
src/Kaponata.Sidecars/PairingRecordProvisioner.cs
src/Kaponata.iOS.Tests/DependencyInjection/DeviceServiceProviderTests.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS/DependencyInjection/DeviceServiceProvider.cs
src/Kaponata.iOS/DependencyInjection/ServiceCollectionExtensions.cs

The `DeviceServiceProvider` class is a simple class which wraps around the `IServiceProvider` and exposes methods to interact with lockdown services running on iOS devices.
The `CreateDeviceScopeAsync` and `StartServiceAsync` methods replace the extension methods on the `IServiceProvider` interface, making these methods easier to mock.
There are no function changes in this PR.

Introducing the DeviceServiceProvider

---

src/Kaponata.Sidecars.Tests/DeveloperDiskProvisionerTests.cs
src/Kaponata.Sidecars/DeveloperDiskProvisioner.cs
src/Kaponata.iOS/DependencyInjection/DeviceServiceScope.cs
src/Kaponata.iOS/MobileImageMounter/MobileImageMounterClient.cs

This provisioner is responsible for:
- Determining whether a developer disk is already mounted
- Determining whether a matching developer disk is available in the developer disk store
- Mounting the matching developer disk when required

Add the DeveloperDiskProvisioner class

---

src/Kaponata.Api/Dockerfile
src/Kaponata.Api/Makefile
src/kaponata-ui/package.json

CORS `AllowAnyOrigin()` is only set when running `Kaponata.Api` in debug mode. 
building and deploying `Kaponata.Api` can be done using:
```
make clean
make deploy TARGET=Debug
```

add debug build option to api makefile

---

src/Kaponata.Kubernetes.Tests/Models/MobileDeviceConditionTests.cs
src/Kaponata.Kubernetes.Tests/Models/MobileDeviceStatusTests.cs
src/Kaponata.Kubernetes/Models/ConditionStatus.cs
src/Kaponata.Kubernetes/Models/MobileDevice.yaml
src/Kaponata.Kubernetes/Models/MobileDeviceCondition.cs
src/Kaponata.Kubernetes/Models/MobileDeviceConditions.cs
src/Kaponata.Kubernetes/Models/MobileDeviceStatus.cs
src/kaponata-ui/package.json

For a device to work properly with Kaponata, multiple conditions must be met. For example:
- The device must pair with the host
- The developer disk image must be mounted on the device.
- A provisioning profile and developer certificate which allow installing applications on the device must be available.
- ...
This PR adds a conditions list to the MobileDevice CRD, which allows storing these conditions. Conditions are described in the [Kubernetes API conventions](https://github.com/zecke/Kubernetes/blob/master/docs/devel/api-conventions.md#typical-status-properties) document.
This PR needs unit tests/integration tests before merging.

Support device conditions.

---

src/Kaponata.Kubernetes.Tests/Models/ModelIntegrationTests.cs
src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientExtensionsTests.MobileDevice.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClientExtensions.MobileDevice.cs
src/Kaponata.Sidecars.Tests/UsbmuxdSidecarTests.cs
src/Kaponata.Sidecars/UsbmuxdSidecar.cs

This PR updates the usbmuxd sidecar so that it uses `MobileDevice.Status.Conditions` to let users of the cluster know whether the device has paired successfully with the host or not.
This has a couple of advantages over creating the device only after the device has paired:
- It makes it easier for users to get the current device state
- It allows us to provide fine-grained status information (e.g.: did the device pair? was the developer disk mounted? ...)

iOS MobileDevice resources: Use Status.Conditions

---

src/Kaponata.Kubernetes/Kaponata.Kubernetes.csproj
src/Kaponata.Kubernetes/KubernetesClient.cs

This contains a small fix which allows us to propagate the underlying exception when throwing a KubernetesException

Bump KubernetesClient to 5.0.10

---

src/Kaponata.Api/Kaponata.Api.csproj
src/Kaponata.Api/Program.cs
src/Kaponata.Operator/Kaponata.Operator.csproj
src/Kaponata.Operator/Program.cs
src/Kaponata.Sidecars/Kaponata.Sidecars.csproj
src/Kaponata.Sidecars/Program.cs

Should make it a bit easier to verify the correct version is running.

Operator, API server and sidecar: print version info on startup

---

src/Kaponata.Kubernetes.Tests/KubernetesClientTests.cs
src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientTests.cs
src/Kaponata.Kubernetes.Tests/Polyfill/KubernetesProtocolTests.Watch.cs
src/Kaponata.Kubernetes/KubernetesClient.NamespacedObject.cs
src/Kaponata.Kubernetes/KubernetesClient.Pods.cs
src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs
src/Kaponata.Kubernetes/Polyfill/IKubernetesProtocol.cs
src/Kaponata.Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/FakeOperatorIntegrationTests.cs
src/Kaponata.Operator.Tests/Operators/KubernetesClientMockExtensions.cs
src/Kaponata.Operator/Operators/ChildOperator.cs
src/Kaponata.Tests.Shared/NamespacedKubernetesClientExtensions.cs

Various operations (such as the list and watch operations) take a `resourceVersion` argument, which allows you to specify which version of a resource you want to retrieve.
It is possible for exact resource versions of objects the be unavailable, when these objects are not updated frequently.
In that case, we can pass `resourceVersionMatch =NotOlderThan`, allowing the cluster to return newer versions of that object.

List & Watch operations: Support the resourceVersionMatch parameter

---

src/Kaponata.Sidecars/PairingRecordProvisioner.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Pair.cs
src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Session.cs
src/Kaponata.iOS.Tests/Lockdown/PairingRecordTests.cs
src/Kaponata.iOS/Lockdown/LockdownError.cs
src/Kaponata.iOS/Lockdown/PairingRecord.cs

- `LockdownError`: Fix `InvalidHostID` spelling
- `PairingRecord`: Implement `.ToString()`
- `PairingRecordProvisioner`: Additional logging

Various fixes

---

src/chart/charts/usbmuxd/templates/daemonset.yaml

We force the usbmudx pod to listen on a TCP socket. This means that the muxer client should also connect to this TCP address. Set the `USBMUXD_SOCKET_ADDRESS` environment variable to achieve that.

usbmuxd pod: set USBMUXD_SOCKET_ADDRESS

---

src/Directory.Build.props
src/Kaponata.Sidecars.Tests/UsbmuxdSidecarTests.cs
src/Kaponata.Sidecars/Makefile
src/Kaponata.Sidecars/UsbmuxdSidecar.cs

The sidecar currently selects iOS devices based on the OS, the UDID and the "owner" (= the name of the usbmuxd pod to which the device is attached).
That doesn't work well for devices which were previously attached to a pod with a different name. This can happen when the pod is re-created, or when the device is physically moved from one node to another.
Only use the OS + the UDID of the device to uniquely identifier a device.
This commit also adds more logging.

UsbmuxdSidecar: Use the UDID of the device as a unique identifier

---

.github/workflows/build.yaml

Redroid uses the ashmem and binder Linux kernel modules.
These modules are part of the Linux source tree, but not built for the Azure flavour of Ubuntu. We build them from source instead.
Unfortunately, the kernel modules use `kallsyms_lookup_name` which have been deprecated in newer versions of the Linux kernel: https://lwn.net/Articles/813350/.
The GitHub actions VMs recently started using a newer version of Linux, breaking the kernel modules required by Redroid.
This commit removes Redroid from CI until this issue is fixed upstream (e.g. via https://github.com/anbox/anbox-modules/pull/76).

Remove Redroid from CI

---

src/chart/charts/usbmuxd/templates/usbmuxd-role.yaml

The usbmuxd sidecar will store the pairing records for iOS devices as secrets in the cluster.
This commit grants the usbmuxd role access to cluster secrets.

usbmuxd role: Allow access to secrets

---

src/chart/charts/usbmuxd/templates/usbmuxd-role.yaml

The usbmuxd sidecar will update the status of mobile device objects by patching the status. This is considered a separate resource by Kubernetes (`mobiledevices/status` vs `mobiledevices`).
This commit updates the role and grants the usbmuxd pod access to the `mobiledevice/status` resource.

Grant usbmuxd access to mobiledevice/patch
