kaponata-io/kaponata

src/iproxy/Dockerfile, src/iproxy/Makefile, src/usbmuxd/Dockerfile, src/usbmuxd/Makefile
Use the annotations as recommended by the OCI specification:
https://github.com/opencontainers/image-spec/blob/master/annotations.md
Use nbgv to get metadata.
=> Annotate Docker images

src/Directory.Build.props, src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientIntegrationTests.cs, src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.cs, src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs, src/Kaponata.Operator.Tests/Kubernetes/Polyfill/WatchHandlerTests.cs, src/Kaponata.Operator/Kubernetes/KubernetesMuxerSocketLocator.cs, src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.PortForward.cs
And fix a bunch of warnings while we're at it.
=> Enable TreatWarningsAsErrors

src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
Replace the `SimplexStream` by a simple mock of a `Stream` which never completes I/O, and cancels I/O when being disposed of. This should capture the spirit of the test, and reduce any dependencies.
=> Attempt to fix WatchPodAsync_CancelsIfNeeded_Async flakiness by simplifying test

src/Kaponata.Android.Tests/Adb/AdbClientCommandsTest.cs, src/Kaponata.Android.Tests/Adb/AdbClientTests.cs, src/Kaponata.Android.Tests/Adb/AdbProtocolTests.cs, src/Kaponata.Android.Tests/Adb/AdbResponseTests.cs, src/Kaponata.Android.Tests/Adb/AdbSocketLocatorTests.cs, src/Kaponata.Android.Tests/Adb/DeviceDataTests.cs, src/Kaponata.Android.Tests/Adb/HexPrimitivesTest.cs, src/Kaponata.Android.Tests/Kaponata.Android.Tests.csproj, src/Kaponata.Android/Adb/AdbClient.Commands.cs, src/Kaponata.Android/Adb/AdbClient.cs, src/Kaponata.Android/Adb/AdbProtocol.cs, src/Kaponata.Android/Adb/AdbResponse.cs, src/Kaponata.Android/Adb/AdbResponseStatus.cs, src/Kaponata.Android/Adb/AdbSocketLocator.cs, src/Kaponata.Android/Adb/ConnectionState.cs, src/Kaponata.Android/Adb/DeviceData.Serialization.cs, src/Kaponata.Android/Adb/DeviceData.cs, src/Kaponata.Android/Adb/HexPrimitives.cs, src/Kaponata.Android/Kaponata.Android.csproj
This PR adds a basic ADB client with currently two supported commands: GetAdbVersion and GetDevices.
=> Add adb client

.github/workflows/build.yaml, src/Kaponata.Operator.Tests/Kubernetes/KubernetesClientTests.MobileDevice.cs, src/Kaponata.Operator.Tests/Kubernetes/Polyfill/KubernetesProtocolTests.Watch.cs
This removed the 'x' flag which causes steps to fail whenever an individual command fails.
=> Remove 'set -e ' in CI

src/Kaponata.Android.Tests/Adb/AdbClientCommandsTest.cs, src/Kaponata.Android.Tests/Adb/AdbExceptionTests.cs, src/Kaponata.Android.Tests/Adb/AdbProtocolTests.cs, src/Kaponata.Android/Adb/AdbClient.Commands.cs, src/Kaponata.Android/Adb/AdbException.cs, src/Kaponata.Android/Adb/AdbProtocol.cs
This PR add the possibility to push and install an apk to an Android device.
=> install apk

.github/workflows/build.yaml, src/Kaponata.Chart.Tests/ApiTests.cs, src/chart/Makefile, src/chart/templates/_helpers.tpl, src/chart/templates/api-deployment.yaml, src/chart/templates/api-ingress.yaml, src/chart/templates/api-service.yaml, src/chart/templates/api-serviceAccount.yaml, src/chart/values.yaml
- Add the API server to the Helm chart
- Route `/api` requests to the API server
=> Package the API server

.github/workflows/images.yaml, src/fake-driver/Dockerfile, src/fake-driver/Makefile
May be useful for integration testing.
=> Add appium-fake-driver image

src/Kaponata.Operator.Tests/Kubernetes/SelectorTests.cs, src/Kaponata.Operator.Tests/Operators/KubernetesClientMockExtensions.cs, src/Kaponata.Operator.Tests/Operators/RedroidOperatorTests.cs, src/Kaponata.Operator/Kubernetes/Selector.cs, src/Kaponata.Operator/Operators/RedroidOperator.cs, src/Kaponata.Operator/Startup.cs
The Redroid operator watches for containers running Redroid Android and creates a MobileDevice object for each running container.
=> Add the Redroid operator

.github/workflows/build.yaml, .github/workflows/website.yaml, website/docs/class/index.md, website/docs/overrides/home.html, website/mkdocs.yml
Push the published website to CI storage _if_ the website has changed.
=> Enable Website previews

src/Kaponata.Operator/Kaponata.Operator.csproj, src/Kaponata.Operator/Kubernetes/Polyfill/IKubernetesProtocol.cs, src/Kaponata.Operator/Kubernetes/Polyfill/KubernetesProtocol.cs
Remove workarounds for:
- https://github.com/kubernetes-client/csharp/pull/548
- https://github.com/kubernetes-client/csharp/pull/550
=> Bump KubernetesClient to 4.0.10

src/Kaponata.Operator/Models/WebDriverSession.yaml, src/Kaponata.Operator/Models/WebDriverSessionStatus.cs
These values will be populated when a session is provisioned successfully
=> WebDriverSession: Add sessionId, capabilities to status

src/Kaponata.Android.Tests/Adb/AdbClientForwardTests.cs, src/Kaponata.Android.Tests/Adb/AdbClientTests.cs, src/Kaponata.Android.Tests/Adb/ForwardDataTests.cs, src/Kaponata.Android.Tests/Adb/ForwardSpecTests.cs, src/Kaponata.Android.Tests/Adb/ShellStreamTests.cs, src/Kaponata.Android/Adb/AdbClient.Forward.cs, src/Kaponata.Android/Adb/AdbClient.Services.cs, src/Kaponata.Android/Adb/AdbClient.cs, src/Kaponata.Android/Adb/ForwardData.Serialization.cs, src/Kaponata.Android/Adb/ForwardData.cs, src/Kaponata.Android/Adb/ForwardProtocol.cs, src/Kaponata.Android/Adb/ForwardSpec.Serialization.cs, src/Kaponata.Android/Adb/ForwardSpec.cs
add ADBclient methods for ADB forward and ADB reverse:
- list
- remove
- remove-all
- create
=> add adb forward and adb reverse API

src/Kaponata.Operator.Tests/Operators/ChildOperatorTests.cs, src/Kaponata.Operator/Operators/ChildOperator.cs
=> Prevent concurrent executions of ProcessBufferedReconciliationsAsync

src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientTests.cs, src/Kaponata.Kubernetes.Tests/Polyfill/KubernetesProtocolTests.Watch.cs, src/Kaponata.Kubernetes/KubernetesClient.NamespacedObject.cs, src/Kaponata.Kubernetes/KubernetesClient.cs, src/Kaponata.Kubernetes/NamespacedKubernetesClient.cs, src/Kaponata.Kubernetes/Polyfill/KubernetesProtocol.Watch.cs
- Handle bookmark events
- Reconnect when the server disconnects
=> NamespacedKubernetesClient: Improve Watch loop

src/Kaponata.Multimedia.Tests/AVCodecDescriptorTests.cs, src/Kaponata.Multimedia.Tests/AVCodecParametersTests.cs, src/Kaponata.Multimedia.Tests/AVCodecTests.cs, src/Kaponata.Multimedia.Tests/AVDictionaryHelpersTests.cs, src/Kaponata.Multimedia.Tests/AVFormatContextHandleTests.cs, src/Kaponata.Multimedia.Tests/AVFormatContextTests.cs, src/Kaponata.Multimedia.Tests/AVIOContextHandleTests.cs, src/Kaponata.Multimedia.Tests/AVIOContextTests.cs, src/Kaponata.Multimedia.Tests/AVMemoryHandleTests.cs, src/Kaponata.Multimedia.Tests/AVRationalTests.cs, src/Kaponata.Multimedia.Tests/AVStreamTests.cs, src/Kaponata.Multimedia.Tests/FFmpegClientLibrariesTests.cs, src/Kaponata.Multimedia/FFmpeg/AVCodecCapabilities.cs, src/Kaponata.Multimedia/FFmpeg/AVCodecDescriptor.cs, src/Kaponata.Multimedia/FFmpeg/AVCodecParameters.cs, src/Kaponata.Multimedia/FFmpeg/AVCodecProps.cs, src/Kaponata.Multimedia/FFmpeg/AVDictionaryHelpers.cs, src/Kaponata.Multimedia/FFmpeg/AVFormatContext.cs, src/Kaponata.Multimedia/FFmpeg/AVFormatContextEventFlags.cs, src/Kaponata.Multimedia/FFmpeg/AVFormatContextFlags.cs, src/Kaponata.Multimedia/FFmpeg/AVFormatContextHandle.cs, src/Kaponata.Multimedia/FFmpeg/AVIOContext.cs, src/Kaponata.Multimedia/FFmpeg/AVIOContextHandle.cs, src/Kaponata.Multimedia/FFmpeg/AVMemoryHandle.cs, src/Kaponata.Multimedia/FFmpeg/AVRational.cs, src/Kaponata.Multimedia/FFmpeg/AVStream.cs, src/Kaponata.Multimedia/FFmpeg/AvCodec.cs, src/Kaponata.Multimedia/FFmpeg/FFmpegClient.Libraries.cs, src/Kaponata.Multimedia/FFmpeg/FFmpegClient.Release.cs, src/Kaponata.Multimedia/FFmpeg/FFmpegClient.cs
The PR aligns the FFmpeg naming to the original project
=> Rename FFMpeg to FFmpeg

src/Kaponata.Kubernetes.Tests/KubernetesClientIntegrationTests.cs, src/Kaponata.Operator.Tests/Kubernetes/KubernetesAdbSocketLocatorTests.cs, src/Kaponata.Operator.Tests/Operators/ChildOperatorIntegrationTests.cs, src/Kaponata.Operator/Kaponata.Operator.csproj, src/Kaponata.Operator/Kubernetes/KubernetesAdbSocketLocator.cs
Allows creating an AdbClient instance which connects to adb running inside a Kubernetes pod
=> Add KubernetesAdbSocketLocator

src/Kaponata.Api.Tests/KubernetesWebDriverTests.cs, src/Kaponata.Api/KubernetesWebDriver.cs
Make the front-end accept `platformName: android` and `automationName: uiautomator2` sessions.
=> KubernetesWebDriver: Add uiautomator2 support

ci/kaponata/Vagrantfile, ci/kaponata/playbook.yml
This adds a Vagrant environment which can be used for dev/test purposes.
=> Add Vagrant configuration

src/Kaponata.Operator/Dockerfile
Add a missing description to the Kaponata operator.
=> Add operator description

src/Kaponata.Sidecars.Tests/Kaponata.Sidecars.Tests.csproj, src/Kaponata.Sidecars.Tests/ProgramTests.cs, src/Kaponata.Sidecars.Tests/UsbmuxdSidecarTests.cs, src/Kaponata.Sidecars/Program.cs, src/Kaponata.Sidecars/UsbmuxdSidecar.cs, src/Kaponata.Sidecars/UsbmuxdSidecarConfiguration.cs, src/Kaponata.iOS/Muxer/MuxerClient.Listen.cs, src/Kaponata.iOS/Muxer/MuxerClient.cs
Add a reconcilation loop which replicates usbmuxd device lists to Kubernetes device lists.
=> Add usbmuxd sidecar implementation

src/Kaponata.iOS.Tests/Muxer/BuidMessageTests.cs, src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.ReadBuid.cs, src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.cs, src/Kaponata.iOS.Tests/Muxer/MuxerMessageTests.cs, src/Kaponata.iOS.Tests/Muxer/buid.xml, src/Kaponata.iOS/Muxer/BuidMessage.Serialization.cs, src/Kaponata.iOS/Muxer/BuidMessage.cs, src/Kaponata.iOS/Muxer/MuxerClient.ReadBuid.cs, src/Kaponata.iOS/Muxer/MuxerMessage.Serialization.cs
This allows retrieving the System BUID used by the usbmuxd instance.
=> Add MuxerClient.ReadBuidAsync

src/Kaponata.iOS.Tests/Muxer/ConnectMessageTests.cs, src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.Connect.cs, src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.cs, src/Kaponata.iOS/Muxer/ConnectMessage.cs, src/Kaponata.iOS/Muxer/MuxerClient.Connect.cs, src/Kaponata.iOS/Muxer/MuxerClient.cs, src/Kaponata.iOS/Muxer/MuxerError.cs, src/Kaponata.iOS/Muxer/MuxerProtocol.cs
This allows connecting to TCP ports on the iOS device.
=> Add MuxerClient.Connect

src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.Pair.cs, src/Kaponata.iOS.Tests/Lockdown/PairRequestTests.cs, src/Kaponata.iOS.Tests/Lockdown/PairingOptionsTests.cs, src/Kaponata.iOS/Lockdown/LockdownClient.Pair.cs, src/Kaponata.iOS/Lockdown/PairRequest.cs, src/Kaponata.iOS/Lockdown/PairResult.cs, src/Kaponata.iOS/Lockdown/PairingOptions.cs, src/Kaponata.iOS/Lockdown/PairingRecord.cs
This can be used to pair a device with a host.
=> Add LockdownClient.Pair, Unpair and ValidatePair methods

src/Kaponata.Android.Tests/Adb/AdbClientListenTests.cs, src/Kaponata.Android/Adb/AdbClient.Listen.cs, src/Kaponata.Android/Adb/AdbListenAction.cs
Implements AdbClient.Listen to monitor the devices each time a device is connected or disconnected.
=> add adb device monitor

src/Kaponata.Chart.Tests/UsbmuxdTests.cs, src/Kaponata.Kubernetes.Tests/PairingRecords/KubernetesPairingRecordStoreIntegrationTests.cs, src/Kaponata.Kubernetes.Tests/PairingRecords/KubernetesPairingRecordStoreTests.cs, src/Kaponata.Kubernetes.Tests/PairingRecords/V1SecretExtensionsTests.cs, src/Kaponata.iOS.Tests/GlobalSuppressions.cs, src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.GetValue.cs, src/Kaponata.iOS.Tests/Lockdown/LockdownClientTests.SetValue.cs, src/Kaponata.iOS.Tests/Lockdown/PairingRecordGeneratorTests.cs, src/Kaponata.iOS.Tests/Lockdown/SetValueRequestTests.cs, src/Kaponata.iOS.Tests/Muxer/MuxerClientTests.ReadBuid.cs, src/Kaponata.iOS.Tests/Workers/PairingWorkerTests.cs, src/Kaponata.iOS/ClientFactory.cs, src/Kaponata.iOS/DependencyInjection/ServiceCollectionExtensions.cs, src/Kaponata.iOS/GlobalSuppressions.cs, src/Kaponata.iOS/Lockdown/LockdownClient.GetValue.cs, src/Kaponata.iOS/Lockdown/LockdownClient.Pair.cs, src/Kaponata.iOS/Lockdown/LockdownClient.SetValue.cs, src/Kaponata.iOS/Lockdown/LockdownClientFactory.cs, src/Kaponata.iOS/Lockdown/PairingRecordGenerator.cs, src/Kaponata.iOS/Lockdown/SetValueRequest.cs, src/Kaponata.iOS/Muxer/MuxerClient.ReadBuid.cs, src/Kaponata.iOS/NotificationProxy/NotificationProxyClient.cs, src/Kaponata.iOS/NotificationProxy/NotificationProxyClientFactory.cs, src/Kaponata.iOS/Workers/PairingWorker.cs
The methods in this class take care of pairing a device with a host.
=> Add the PairingWorker class

src/Kaponata.Kubernetes.Tests/Registry/ImageTests.cs, src/Kaponata.Kubernetes/Annotations.cs, src/Kaponata.Kubernetes/Registry/History.cs, src/Kaponata.Kubernetes/Registry/Image.cs, src/Kaponata.Kubernetes/Registry/ImageConfig.cs, src/Kaponata.Kubernetes/Registry/RootFS.cs
=> Support writing OCI Image Configuration specifications

src/Kaponata.Kubernetes.Tests/Registry/ManifestTests.cs, src/Kaponata.Kubernetes/Registry/Descriptor.cs, src/Kaponata.Kubernetes/Registry/Manifest.cs, src/Kaponata.Kubernetes/Registry/Platform.cs
=> Support writing OCI Image Manifest specifications.

src/Kaponata.FileFormats.Tests/Tar/TarReaderTests.cs, src/Kaponata.FileFormats.Tests/Tar/TarWriterTests.cs, src/Kaponata.FileFormats/Tar/TarReader.cs, src/Kaponata.FileFormats/Tar/TarWriter.cs
=> Add support for reading and writing Tar archives

src/Kaponata.FileFormats.Tests/Lzfse/LzfseCompressorTests.cs, src/Kaponata.FileFormats/Dmg/UdifBuffer.cs, src/Kaponata.FileFormats/Kaponata.FileFormats.csproj, src/Kaponata.FileFormats/Lzfse/LzfseCompressor.cs, src/Kaponata.FileFormats/Lzfse/NativeMethods.cs
Port of https://github.com/quamotion/lzfse-net/
=> Add LZFSE compression/decompression support

src/Kaponata.FileFormats.Tests/Cpio/CpioFileTests.cs, src/Kaponata.FileFormats.Tests/Dmg/DiskImageFileTests.cs, src/Kaponata.FileFormats.Tests/Kaponata.FileFormats.Tests.csproj, src/Kaponata.FileFormats/Cpio/CpioFile.cs, src/Kaponata.FileFormats/Cpio/CpioHeader.cs
.xip/.xar files use CPIO, so add support for reading CPIO data.
=> Add CPIO support

src/Kaponata.FileFormats.Tests/Dmg/DiskImageFileTests.cs, src/Kaponata.FileFormats.Tests/HfsPlus/HfsPlusDirectoryTests.cs, src/Kaponata.FileFormats.Tests/Kaponata.FileFormats.Tests.csproj, src/Kaponata.FileFormats.Tests/Xar/XarFileTests.cs, src/Kaponata.FileFormats.Tests/Xip/XipFileTests.cs, src/Kaponata.iOS.Tests/AppleVersionTests.cs, src/Kaponata.iOS.Tests/DeveloperDisks/DeveloperDiskReaderTests.cs, src/Kaponata.iOS.Tests/DeveloperDisks/SystemVersionTests.cs, src/Kaponata.iOS.Tests/GlobalSuppressions.cs, src/Kaponata.iOS.Tests/Kaponata.iOS.Tests.csproj, src/Kaponata.iOS/AppleVersion.cs, src/Kaponata.iOS/DeveloperDisks/DeveloperDiskReader.cs, src/Kaponata.iOS/DeveloperDisks/SystemVersion.cs, src/Kaponata.iOS/GlobalSuppressions.cs, src/Kaponata.iOS/Kaponata.iOS.csproj, src/Kaponata.iOS/PropertyLists/IPropertyListDeserializable.cs
Support reading the version information embedded in the the developer disk images.
=> Support reading the version of a developer disk image

src/Kaponata.Kubernetes.Tests/Registry/DescriptorTests.cs, src/Kaponata.Kubernetes/Registry/Descriptor.cs, src/Kaponata.iOS.Tests/DeveloperDisks/SystemVersionTests.cs, src/Kaponata.iOS/DeveloperDisks/SystemVersion.cs
- `Descriptor`: Add `CreateAsync`
- `SystemVersion`: Add `ToDictionary`
=> Descriptor, SystemVersion updates

src/Kaponata.Kubernetes.Tests/NamespacedKubernetesClientExtensionsTests.MobileDevice.cs, src/Kaponata.Kubernetes/NamespacedKubernetesClientExtensions.MobileDevice.cs
- Add the device status if it is null
- Add the device status conditions if they are null
- Replace the device status conditions if they are not null
=> SetDeviceConditionAsync: Correctly formulate Patch structure

src/Kaponata.Kubernetes.Tests/Licensing/LicenseStoreTests.cs, src/Kaponata.Kubernetes/KubernetesClient.cs, src/Kaponata.Kubernetes/KubernetesServiceCollectionExtensions.cs, src/Kaponata.Kubernetes/Licensing/LicenseStore.cs
Used for storing Kaponata/Quamotion licenses
=> Add the LicenseStore

src/Kaponata.Api.Tests/LicenseControllerTests.cs, src/Kaponata.Api/LicenseController.cs
This adds the following endpoints:
```
POST /api/license
GET /api/license
```
for managing licenses
=> Add LicenseController

src/Kaponata.Kubernetes.Tests/Registry/ImageRegistryClientTests.cs, src/Kaponata.Kubernetes/Registry/ImageRegistryClient.cs
returns an empty tag list when the repository is not found.
=> returns an empty tag list when the repository is not found.

src/Kaponata.Api/DeveloperDiskController.cs, src/Kaponata.Api/Startup.cs, src/kaponata-ui/e2e/src/app.e2e-spec.ts, src/kaponata-ui/e2e/src/settings.po.ts, src/kaponata-ui/src/app/app.module.ts, src/kaponata-ui/src/app/developer-disk-service.ts, src/kaponata-ui/src/app/developer-disk-upload/developer-disk-upload.component.html, src/kaponata-ui/src/app/developer-disk-upload/developer-disk-upload.component.ts, src/kaponata-ui/src/app/file-upload/file-upload.component.html, src/kaponata-ui/src/app/file-upload/file-upload.component.scss, src/kaponata-ui/src/app/file-upload/file-upload.component.ts, src/kaponata-ui/src/app/provisioning-profile.service.ts, src/kaponata-ui/src/app/settings.component.html, src/kaponata-ui/src/app/settings.component.ts
The PR adds some functionality to the settings page:
- add provisioning profile
- list developer disks
- add developer disk
=> adding provisioning profile and developer disk options to settings page

.github/workflows/build.yaml, .github/workflows/website.yaml, .vscode/launch.json, src/kaponata-ui/angular.json
This PR disables the optimization and enables sourcemaps for non production builds (kaponata-ui)
=> Enable debugging

.github/workflows/build.yaml, .vscode/launch.json, ci/playbook.yml, src/Kaponata.Api/DeveloperCertificateController.cs, src/kaponata-ui/e2e/src/app.e2e-spec.ts, src/kaponata-ui/src/app/app.module.ts, src/kaponata-ui/src/app/developer-certificate-upload/developer-certificate-upload.component.html, src/kaponata-ui/src/app/developer-certificate-upload/developer-certificate-upload.ts, src/kaponata-ui/src/app/developer-certificate.service.ts, src/kaponata-ui/src/app/developer-disk-upload/developer-disk-upload.component.ts, src/kaponata-ui/src/app/developer-profile-service.ts, src/kaponata-ui/src/app/developer-profile-upload/developer-profile-upload.component.html, src/kaponata-ui/src/app/developer-profile-upload/developer-profile-upload.ts, src/kaponata-ui/src/app/http-interceptors/error-interceptor.ts, src/kaponata-ui/src/app/settings.component.html, src/kaponata-ui/src/app/settings.component.ts
This PR adds the possibility to upload certificates and developer profiles from the UI.
=> add certificate and developerprofile upload
